language: java
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=phyzicsz_rocketdis
jdk:
- openjdk11
branches:
  only:
  - master
  - development
addons:
  sonarcloud:
    organization: phyzicsz
    token:
      secure: RKmJALfPRbWd1OVbfs325ilHf4BFTpVDhvVBgM5QQ7JwlqhGoYyjO4kF8T40cI/+W3k5rz7wJWktW0QxvyZsA4nooDgvpEX/cSZXkZ0dKiuNddgIn65jgFIH/5WGtekkL0RLS2lMVKcnqegA5iUM+JlujqX1n4miP8VIHXUkMoCWH7J/bMaV3RXHRq4bsdgWqa+oNXeJXqQoUrtm01Vas4OUYAeL8/n0x2OhAjBSimBGjKz97Xn9SDbicXNcGdVAhMZFHiT9nAeKuL1/v2yB0Bg25+CIrnADtWwbW+fBofMBUuSqF4em5z7hwZwEYpZWdqMBn5HqLwBVbetO/vOu4Zx2msv+2xjTmZu1TLxON4e1YNlJzWSXzt8NRW98GPqd8EsAbOVN5ZUpGb0rwzJkXz14RytCIuQF1J96ZtLX9teDRqktaPtb19PHwvEV2ucdEagUUQmN6LLubqXNlfNWUS+mZkizbpqrCyHFicy63NBq+chzMgN1WE5NRP7mleo3EfGJkrFkJYwmCC6pb4Oy/5r3ubhYXOIbay+sXCSMLlNyNGfJGAPuL6cOE+KB3a5Jr9GBeyp59DWXtJ4fGlBiGSeYjrCptHyr9AJrb8/joNF0O6VLfxYOkjiY3ktunloIDPMyQIFEoa79whoykdSqz0YI5codSrmSjFGRgV1iD9Q=

